// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/worker/accrual/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/worker/accrual/interfaces.go -destination=./internal/worker/accrual/mocks.go -package=accrual
//

// Package accrual is a generated GoMock package.
package accrual

import (
	context "context"
	reflect "reflect"

	entity "github.com/NoobyTheTurtle/gophermart/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockLogger) Error(message string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(message any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *MockLogger) Info(message string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(message any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), varargs...)
}

// MockAccrualUseCase is a mock of AccrualUseCase interface.
type MockAccrualUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualUseCaseMockRecorder
	isgomock struct{}
}

// MockAccrualUseCaseMockRecorder is the mock recorder for MockAccrualUseCase.
type MockAccrualUseCaseMockRecorder struct {
	mock *MockAccrualUseCase
}

// NewMockAccrualUseCase creates a new mock instance.
func NewMockAccrualUseCase(ctrl *gomock.Controller) *MockAccrualUseCase {
	mock := &MockAccrualUseCase{ctrl: ctrl}
	mock.recorder = &MockAccrualUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualUseCase) EXPECT() *MockAccrualUseCaseMockRecorder {
	return m.recorder
}

// GetOrdersForProcessing mocks base method.
func (m *MockAccrualUseCase) GetOrdersForProcessing(ctx context.Context) ([]*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersForProcessing", ctx)
	ret0, _ := ret[0].([]*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersForProcessing indicates an expected call of GetOrdersForProcessing.
func (mr *MockAccrualUseCaseMockRecorder) GetOrdersForProcessing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersForProcessing", reflect.TypeOf((*MockAccrualUseCase)(nil).GetOrdersForProcessing), ctx)
}

// ProcessOrder mocks base method.
func (m *MockAccrualUseCase) ProcessOrder(ctx context.Context, orderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessOrder", ctx, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessOrder indicates an expected call of ProcessOrder.
func (mr *MockAccrualUseCaseMockRecorder) ProcessOrder(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessOrder", reflect.TypeOf((*MockAccrualUseCase)(nil).ProcessOrder), ctx, orderNumber)
}
