// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/order/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/order/interfaces.go -destination=./internal/usecase/order/mocks.go -package=order
//

// Package order is a generated GoMock package.
package order

import (
	context "context"
	reflect "reflect"

	entity "github.com/NoobyTheTurtle/gophermart/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepo is a mock of OrderRepo interface.
type MockOrderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepoMockRecorder
	isgomock struct{}
}

// MockOrderRepoMockRecorder is the mock recorder for MockOrderRepo.
type MockOrderRepoMockRecorder struct {
	mock *MockOrderRepo
}

// NewMockOrderRepo creates a new mock instance.
func NewMockOrderRepo(ctrl *gomock.Controller) *MockOrderRepo {
	mock := &MockOrderRepo{ctrl: ctrl}
	mock.recorder = &MockOrderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepo) EXPECT() *MockOrderRepoMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderRepo) CreateOrder(ctx context.Context, order *entity.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderRepoMockRecorder) CreateOrder(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderRepo)(nil).CreateOrder), ctx, order)
}

// GetOrderByNumber mocks base method.
func (m *MockOrderRepo) GetOrderByNumber(ctx context.Context, number string) (*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByNumber", ctx, number)
	ret0, _ := ret[0].(*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByNumber indicates an expected call of GetOrderByNumber.
func (mr *MockOrderRepoMockRecorder) GetOrderByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByNumber", reflect.TypeOf((*MockOrderRepo)(nil).GetOrderByNumber), ctx, number)
}

// GetOrdersByUserID mocks base method.
func (m *MockOrderRepo) GetOrdersByUserID(ctx context.Context, userID int) ([]*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserID indicates an expected call of GetOrdersByUserID.
func (mr *MockOrderRepoMockRecorder) GetOrdersByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserID", reflect.TypeOf((*MockOrderRepo)(nil).GetOrdersByUserID), ctx, userID)
}

// GetOrdersForProcessing mocks base method.
func (m *MockOrderRepo) GetOrdersForProcessing(ctx context.Context) ([]*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersForProcessing", ctx)
	ret0, _ := ret[0].([]*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersForProcessing indicates an expected call of GetOrdersForProcessing.
func (mr *MockOrderRepoMockRecorder) GetOrdersForProcessing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersForProcessing", reflect.TypeOf((*MockOrderRepo)(nil).GetOrdersForProcessing), ctx)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderRepo) UpdateOrderStatus(ctx context.Context, number string, status entity.OrderStatus, accrual float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, number, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderRepoMockRecorder) UpdateOrderStatus(ctx, number, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderRepo)(nil).UpdateOrderStatus), ctx, number, status, accrual)
}

// MockBalanceRepo is a mock of BalanceRepo interface.
type MockBalanceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepoMockRecorder
	isgomock struct{}
}

// MockBalanceRepoMockRecorder is the mock recorder for MockBalanceRepo.
type MockBalanceRepoMockRecorder struct {
	mock *MockBalanceRepo
}

// NewMockBalanceRepo creates a new mock instance.
func NewMockBalanceRepo(ctrl *gomock.Controller) *MockBalanceRepo {
	mock := &MockBalanceRepo{ctrl: ctrl}
	mock.recorder = &MockBalanceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepo) EXPECT() *MockBalanceRepoMockRecorder {
	return m.recorder
}

// AddAccrual mocks base method.
func (m *MockBalanceRepo) AddAccrual(ctx context.Context, userID int, accrual float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccrual", ctx, userID, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAccrual indicates an expected call of AddAccrual.
func (mr *MockBalanceRepoMockRecorder) AddAccrual(ctx, userID, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccrual", reflect.TypeOf((*MockBalanceRepo)(nil).AddAccrual), ctx, userID, accrual)
}

// CreateBalance mocks base method.
func (m *MockBalanceRepo) CreateBalance(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBalance", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBalance indicates an expected call of CreateBalance.
func (mr *MockBalanceRepoMockRecorder) CreateBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBalance", reflect.TypeOf((*MockBalanceRepo)(nil).CreateBalance), ctx, userID)
}

// MockLuhnService is a mock of LuhnService interface.
type MockLuhnService struct {
	ctrl     *gomock.Controller
	recorder *MockLuhnServiceMockRecorder
	isgomock struct{}
}

// MockLuhnServiceMockRecorder is the mock recorder for MockLuhnService.
type MockLuhnServiceMockRecorder struct {
	mock *MockLuhnService
}

// NewMockLuhnService creates a new mock instance.
func NewMockLuhnService(ctrl *gomock.Controller) *MockLuhnService {
	mock := &MockLuhnService{ctrl: ctrl}
	mock.recorder = &MockLuhnServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLuhnService) EXPECT() *MockLuhnServiceMockRecorder {
	return m.recorder
}

// IsValid mocks base method.
func (m *MockLuhnService) IsValid(number string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValid", number)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValid indicates an expected call of IsValid.
func (mr *MockLuhnServiceMockRecorder) IsValid(number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValid", reflect.TypeOf((*MockLuhnService)(nil).IsValid), number)
}
