// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/balance/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/balance/interfaces.go -destination=./internal/usecase/balance/mocks.go -package=balance
//

// Package balance is a generated GoMock package.
package balance

import (
	context "context"
	reflect "reflect"

	entity "github.com/NoobyTheTurtle/gophermart/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceRepo is a mock of BalanceRepo interface.
type MockBalanceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepoMockRecorder
	isgomock struct{}
}

// MockBalanceRepoMockRecorder is the mock recorder for MockBalanceRepo.
type MockBalanceRepoMockRecorder struct {
	mock *MockBalanceRepo
}

// NewMockBalanceRepo creates a new mock instance.
func NewMockBalanceRepo(ctrl *gomock.Controller) *MockBalanceRepo {
	mock := &MockBalanceRepo{ctrl: ctrl}
	mock.recorder = &MockBalanceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepo) EXPECT() *MockBalanceRepoMockRecorder {
	return m.recorder
}

// AddAccrual mocks base method.
func (m *MockBalanceRepo) AddAccrual(ctx context.Context, userID int, accrual float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccrual", ctx, userID, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAccrual indicates an expected call of AddAccrual.
func (mr *MockBalanceRepoMockRecorder) AddAccrual(ctx, userID, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccrual", reflect.TypeOf((*MockBalanceRepo)(nil).AddAccrual), ctx, userID, accrual)
}

// CreateBalance mocks base method.
func (m *MockBalanceRepo) CreateBalance(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBalance", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBalance indicates an expected call of CreateBalance.
func (mr *MockBalanceRepoMockRecorder) CreateBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBalance", reflect.TypeOf((*MockBalanceRepo)(nil).CreateBalance), ctx, userID)
}

// GetBalanceByUserID mocks base method.
func (m *MockBalanceRepo) GetBalanceByUserID(ctx context.Context, userID int) (*entity.UserBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.UserBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByUserID indicates an expected call of GetBalanceByUserID.
func (mr *MockBalanceRepoMockRecorder) GetBalanceByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByUserID", reflect.TypeOf((*MockBalanceRepo)(nil).GetBalanceByUserID), ctx, userID)
}

// UpdateBalance mocks base method.
func (m *MockBalanceRepo) UpdateBalance(ctx context.Context, balance *entity.UserBalance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockBalanceRepoMockRecorder) UpdateBalance(ctx, balance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockBalanceRepo)(nil).UpdateBalance), ctx, balance)
}
