// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/accrual/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/accrual/interfaces.go -destination=./internal/usecase/accrual/mocks.go -package=accrual
//

// Package accrual is a generated GoMock package.
package accrual

import (
	context "context"
	reflect "reflect"

	entity "github.com/NoobyTheTurtle/gophermart/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAccrualAPI is a mock of AccrualAPI interface.
type MockAccrualAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualAPIMockRecorder
	isgomock struct{}
}

// MockAccrualAPIMockRecorder is the mock recorder for MockAccrualAPI.
type MockAccrualAPIMockRecorder struct {
	mock *MockAccrualAPI
}

// NewMockAccrualAPI creates a new mock instance.
func NewMockAccrualAPI(ctrl *gomock.Controller) *MockAccrualAPI {
	mock := &MockAccrualAPI{ctrl: ctrl}
	mock.recorder = &MockAccrualAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualAPI) EXPECT() *MockAccrualAPIMockRecorder {
	return m.recorder
}

// GetOrderAccrual mocks base method.
func (m *MockAccrualAPI) GetOrderAccrual(ctx context.Context, orderNumber string) (*entity.Accrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderAccrual", ctx, orderNumber)
	ret0, _ := ret[0].(*entity.Accrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderAccrual indicates an expected call of GetOrderAccrual.
func (mr *MockAccrualAPIMockRecorder) GetOrderAccrual(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderAccrual", reflect.TypeOf((*MockAccrualAPI)(nil).GetOrderAccrual), ctx, orderNumber)
}

// MockOrderRepo is a mock of OrderRepo interface.
type MockOrderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepoMockRecorder
	isgomock struct{}
}

// MockOrderRepoMockRecorder is the mock recorder for MockOrderRepo.
type MockOrderRepoMockRecorder struct {
	mock *MockOrderRepo
}

// NewMockOrderRepo creates a new mock instance.
func NewMockOrderRepo(ctrl *gomock.Controller) *MockOrderRepo {
	mock := &MockOrderRepo{ctrl: ctrl}
	mock.recorder = &MockOrderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepo) EXPECT() *MockOrderRepoMockRecorder {
	return m.recorder
}

// GetOrderByNumber mocks base method.
func (m *MockOrderRepo) GetOrderByNumber(ctx context.Context, number string) (*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByNumber", ctx, number)
	ret0, _ := ret[0].(*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByNumber indicates an expected call of GetOrderByNumber.
func (mr *MockOrderRepoMockRecorder) GetOrderByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByNumber", reflect.TypeOf((*MockOrderRepo)(nil).GetOrderByNumber), ctx, number)
}

// GetOrdersForProcessing mocks base method.
func (m *MockOrderRepo) GetOrdersForProcessing(ctx context.Context) ([]*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersForProcessing", ctx)
	ret0, _ := ret[0].([]*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersForProcessing indicates an expected call of GetOrdersForProcessing.
func (mr *MockOrderRepoMockRecorder) GetOrdersForProcessing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersForProcessing", reflect.TypeOf((*MockOrderRepo)(nil).GetOrdersForProcessing), ctx)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderRepo) UpdateOrderStatus(ctx context.Context, number string, status entity.OrderStatus, accrual float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, number, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderRepoMockRecorder) UpdateOrderStatus(ctx, number, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderRepo)(nil).UpdateOrderStatus), ctx, number, status, accrual)
}

// MockBalanceRepo is a mock of BalanceRepo interface.
type MockBalanceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepoMockRecorder
	isgomock struct{}
}

// MockBalanceRepoMockRecorder is the mock recorder for MockBalanceRepo.
type MockBalanceRepoMockRecorder struct {
	mock *MockBalanceRepo
}

// NewMockBalanceRepo creates a new mock instance.
func NewMockBalanceRepo(ctrl *gomock.Controller) *MockBalanceRepo {
	mock := &MockBalanceRepo{ctrl: ctrl}
	mock.recorder = &MockBalanceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepo) EXPECT() *MockBalanceRepoMockRecorder {
	return m.recorder
}

// AddAccrual mocks base method.
func (m *MockBalanceRepo) AddAccrual(ctx context.Context, userID int, accrual float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccrual", ctx, userID, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAccrual indicates an expected call of AddAccrual.
func (mr *MockBalanceRepoMockRecorder) AddAccrual(ctx, userID, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccrual", reflect.TypeOf((*MockBalanceRepo)(nil).AddAccrual), ctx, userID, accrual)
}
