// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/withdrawal/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/withdrawal/interfaces.go -destination=./internal/usecase/withdrawal/mocks.go -package=withdrawal
//

// Package withdrawal is a generated GoMock package.
package withdrawal

import (
	context "context"
	reflect "reflect"

	entity "github.com/NoobyTheTurtle/gophermart/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawalRepo is a mock of WithdrawalRepo interface.
type MockWithdrawalRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalRepoMockRecorder
	isgomock struct{}
}

// MockWithdrawalRepoMockRecorder is the mock recorder for MockWithdrawalRepo.
type MockWithdrawalRepoMockRecorder struct {
	mock *MockWithdrawalRepo
}

// NewMockWithdrawalRepo creates a new mock instance.
func NewMockWithdrawalRepo(ctrl *gomock.Controller) *MockWithdrawalRepo {
	mock := &MockWithdrawalRepo{ctrl: ctrl}
	mock.recorder = &MockWithdrawalRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalRepo) EXPECT() *MockWithdrawalRepoMockRecorder {
	return m.recorder
}

// CreateWithdrawal mocks base method.
func (m *MockWithdrawalRepo) CreateWithdrawal(ctx context.Context, withdrawal *entity.Withdrawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawal", ctx, withdrawal)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithdrawal indicates an expected call of CreateWithdrawal.
func (mr *MockWithdrawalRepoMockRecorder) CreateWithdrawal(ctx, withdrawal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawal", reflect.TypeOf((*MockWithdrawalRepo)(nil).CreateWithdrawal), ctx, withdrawal)
}

// GetWithdrawalsByUserID mocks base method.
func (m *MockWithdrawalRepo) GetWithdrawalsByUserID(ctx context.Context, userID int) ([]*entity.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entity.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalsByUserID indicates an expected call of GetWithdrawalsByUserID.
func (mr *MockWithdrawalRepoMockRecorder) GetWithdrawalsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalsByUserID", reflect.TypeOf((*MockWithdrawalRepo)(nil).GetWithdrawalsByUserID), ctx, userID)
}

// MockBalanceRepo is a mock of BalanceRepo interface.
type MockBalanceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepoMockRecorder
	isgomock struct{}
}

// MockBalanceRepoMockRecorder is the mock recorder for MockBalanceRepo.
type MockBalanceRepoMockRecorder struct {
	mock *MockBalanceRepo
}

// NewMockBalanceRepo creates a new mock instance.
func NewMockBalanceRepo(ctrl *gomock.Controller) *MockBalanceRepo {
	mock := &MockBalanceRepo{ctrl: ctrl}
	mock.recorder = &MockBalanceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepo) EXPECT() *MockBalanceRepoMockRecorder {
	return m.recorder
}

// GetBalanceByUserID mocks base method.
func (m *MockBalanceRepo) GetBalanceByUserID(ctx context.Context, userID int) (*entity.UserBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.UserBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByUserID indicates an expected call of GetBalanceByUserID.
func (mr *MockBalanceRepoMockRecorder) GetBalanceByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByUserID", reflect.TypeOf((*MockBalanceRepo)(nil).GetBalanceByUserID), ctx, userID)
}

// UpdateBalance mocks base method.
func (m *MockBalanceRepo) UpdateBalance(ctx context.Context, balance *entity.UserBalance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockBalanceRepoMockRecorder) UpdateBalance(ctx, balance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockBalanceRepo)(nil).UpdateBalance), ctx, balance)
}

// MockLuhnService is a mock of LuhnService interface.
type MockLuhnService struct {
	ctrl     *gomock.Controller
	recorder *MockLuhnServiceMockRecorder
	isgomock struct{}
}

// MockLuhnServiceMockRecorder is the mock recorder for MockLuhnService.
type MockLuhnServiceMockRecorder struct {
	mock *MockLuhnService
}

// NewMockLuhnService creates a new mock instance.
func NewMockLuhnService(ctrl *gomock.Controller) *MockLuhnService {
	mock := &MockLuhnService{ctrl: ctrl}
	mock.recorder = &MockLuhnServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLuhnService) EXPECT() *MockLuhnServiceMockRecorder {
	return m.recorder
}

// IsValid mocks base method.
func (m *MockLuhnService) IsValid(number string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValid", number)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValid indicates an expected call of IsValid.
func (mr *MockLuhnServiceMockRecorder) IsValid(number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValid", reflect.TypeOf((*MockLuhnService)(nil).IsValid), number)
}
